### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by TommasoVerolaLD** [azesmway/react-native-unity#1]
First of all thanks a lot for this library!
Is it possible to share an example project like the older version ?

**Comment by azesmway** [comment]
Add example
https://github.com/azesmway/react-native-unity/tree/main/example/unity/source

**Comment by GawdZillaa** [comment]
Hey! Question on the setup directions. When it says "Copy from folder "unity" to <Unity_Project_Name> folder and rebuild unity project" am I supposed to copy over the entire unity folder from within the root dir of this project to the root dir of my Unity project?

**Comment by azesmway** [comment]
Hi

https://github.com/azesmway/react-native-unity/tree/main/example/unity
this is a working example of a Unity project with the plugin already configured. you can see everything there

**Comment by GawdZillaa** [comment]
Awesome, took a peek at your example and was able to get my own unity app going. Amazing work on this @azesmway
