### ISSUE TITLE
1.0.9 Integration with expo

### ISSUE THREAD

**Issue by fbcarpinato** [azesmway/react-native-unity#115]
Hey @azesmway, I saw that you merged the expo integration and I'm trying to make it work, but I think that something is missing because the plugin is not getting compiled inside the bundle (I just see the typescript definitions) and I'm guessing that the `app.plugin.js` should be there too. 

At the moment if I just follow the instructions for expo users i get something like 

> Project with path ':unityLibrary' could not be found in project ':azesmway_react-native-unity'.

which suggest that the plugin didn't run

Thanks!

**Comment by azesmway** [comment]
Hi @fbcarpinato 
I haven't dealt with expo and it's hard for me now how it's supposed to work.

**Comment by fbcarpinato** [comment]
Yea, it would be great if @Jpoliachik that wrote the PR could give some help with it

**Comment by fbcarpinato** [comment]
I managed to get a build working by just following the guide as if I didn't have expo.

This is true if I just run `npm run android` and it works on the simulator.

But if I try to get a eas build with expo i get

```[RUN_GRADLEW] FAILURE:
[RUN_GRADLEW] Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Could not determine the dependencies of task ':app:lintVitalReportRelease'.
[RUN_GRADLEW] > Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
[RUN_GRADLEW]    > Could not resolve project :unityLibrary.
[RUN_GRADLEW]      Required by:
[RUN_GRADLEW]          project :app > project :azesmway_react-native-unity
[RUN_GRADLEW]       > No matching configuration of project :unityLibrary was found. The consumer was configured to find a component for use during runtime, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.1.1', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
[RUN_GRADLEW]           - None of the consumable configurations have attributes.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org. ```

**Comment by d487840785** [comment]
Hi, according to the code example you provided, how can I ensure that my message is successfully sent when I send a message to Unity during RN initialization? How should Unity send messages so that I can receive them in the onUnityMessage callback?
![image](https://github.com/azesmway/react-native-unity/assets/103488118/117d1f11-5cbe-43f8-9052-6aa0fb5859f6)

**Comment by fbcarpinato** [comment]
> Hi, according to the code example you provided, how can I ensure that my message is successfully sent when I send a message to Unity during RN initialization? How should Unity send messages so that I can receive them in the onUnityMessage callback? ![image](https://private-user-images.githubusercontent.com/103488118/329163961-117d1f11-5cbe-43f8-9052-6aa0fb5859f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDA5ODksIm5iZiI6MTcxNTI0MDY4OSwicGF0aCI6Ii8xMDM0ODgxMTgvMzI5MTYzOTYxLTExN2QxZjExLTVjYmUtNDNmOC05MDUyLTZhYTBmYjU4NTlmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwNzQ0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZThhMDE3MDA4NmRkOTg5YWYxN2ZiNTE5OGZiZGJlYTRjYTJkMGQyNDAxNmE5ZTViY2EyZjJlMjA1OTJkYWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ovmkFTrMSFakCTGnkTDsreGOkg9z2aO3bOu4uyOL9HI)

this is ot

**Comment by d487840785** [comment]
> > Hi, according to the code example you provided, how can I ensure that my message is successfully sent when I send a message to Unity during RN initialization? How should Unity send messages so that I can receive them in the onUnityMessage callback? ![image](https://private-user-images.githubusercontent.com/103488118/329163961-117d1f11-5cbe-43f8-9052-6aa0fb5859f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDA5ODksIm5iZiI6MTcxNTI0MDY4OSwicGF0aCI6Ii8xMDM0ODgxMTgvMzI5MTYzOTYxLTExN2QxZjExLTVjYmUtNDNmOC05MDUyLTZhYTBmYjU4NTlmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwNzQ0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZThhMDE3MDA4NmRkOTg5YWYxN2ZiNTE5OGZiZGJlYTRjYTJkMGQyNDAxNmE5ZTViY2EyZjJlMjA1OTJkYWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ovmkFTrMSFakCTGnkTDsreGOkg9z2aO3bOu4uyOL9HI)
> 
> this is ot

I don't know Unity, what I get is a package of Unity that has been pre packaged according to the example, and can be displayed normally after using the plugin. However, what I need is communication with each other. I am not sure what Unity needs, or how I can receive messages I send him. Hehe, could you please give me a simple example of Unity that can communicate with each other? I am trying to use it in my practice project. I am a beginner and have not quite understood complex things yet🫠
