### ISSUE TITLE
How to Conditionally Exclude UnityFramework When Building for iOS Simulators?

### ISSUE THREAD

**Issue by carlandren2002** [azesmway/react-native-unity#117]
To facilitate development and testing, I'm looking for a way to conditionally exclude the UnityFramework when building for iOS simulators.

**Issue**:
Currently, the UnityFramework is included in all builds, which causes builds for iOS simulators to fail because the UnityFramework does not support them. This is blocking our development and testing processes on simulators.

**Objective**:
I would like to configure our Xcode project to exclude the UnityFramework when building for simulators but include it when building for actual iOS devices. This way, we can continue to develop and test other parts of our app on simulators without issues.

**Questions**:
1. Is there a recommended approach to conditionally exclude the UnityFramework from builds targeting iOS simulators?
2. Can you provide guidance or documentation on how to set this up in Xcode, possibly using build settings or scripts?

**Attempts**:
I've tried excluding certain architectures under the 'Excluded Architectures' setting in Xcode, but this approach is quite broad and affects the entire application rather than just the UnityFramework.

Any advice or suggestions on how to achieve this would be greatly appreciated!

**Comment by gottfriedaniel** [comment]
@carlandren2002 Can you share how did you eventually solved it?

**Comment by carlandren2002** [comment]
@gottfriedaniel I haven't tried to yet but I think #90 does the job
