### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by ynqq** [azesmway/react-native-unity#12]
### hi When I use this library to go back to the previous page in RN, the whole app crashes. what should I do
https://user-images.githubusercontent.com/45785987/164642884-cb4d97f8-7d0f-42f5-a220-43f422b9fad0.mp4

``` js
04-19 17:13:08.984  5780  5780 E AndroidRuntime: FATAL EXCEPTION: main
04-19 17:13:08.984  5780  5780 E AndroidRuntime: Process: com.app664, PID: 5780
04-19 17:13:08.984  5780  5780 E AndroidRuntime: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.addViewInner(ViewGroup.java:5361)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.addView(ViewGroup.java:5190)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.addView(ViewGroup.java:5162)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.addContentView(AppCompatDelegateImpl.java:716)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.addContentView(AppCompatActivity.java:213)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at com.azesmwayreactnativeunity.ReactNativeUnity.addUnityViewToBackground(ReactNativeUnity.java:108)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at com.azesmwayreactnativeunity.ReactNativeUnityView.onDetachedFromWindow(ReactNativeUnityView.java:58)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.View.dispatchDetachedFromWindow(View.java:20161)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4047)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.clearDisappearingChildren(ViewGroup.java:7214)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4037)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.clearDisappearingChildren(ViewGroup.java:7214)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4037)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4033)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.view.ViewGroup.endViewTransition(ViewGroup.java:7327)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at com.swmansion.rnscreens.ScreenStack.endViewTransition(ScreenStack.kt:56)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at androidx.fragment.app.DefaultSpecialEffectsController$4$1.run(DefaultSpecialEffectsController.java:257)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:900)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:103)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
04-19 17:13:08.984  5780  5780 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
04-19 17:13:08.996  1581  4738 E ActivityManager: do not add repeated dropbox, mLastAppCrashedPid==5780
04-19 17:13:09.056  1132  1448 E Parcel  : Reading a NULL string not supported here.
04-19 17:13:09.121  1581  2086 E InputDispatcher: channel '8ceda09 com.app664/com.app664.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-19 17:13:09.129  1581  2754 E AwareLog: CpuKeyBackground: checkIsTargetGroup read catch IOException msg = /proc/5780/cpuset: open failed: ENOENT (No such file or directory)
04-19 17:13:09.134  2545 10966 E HsmCoreServiceImpl: onTransact in code is: 102
```

**Comment by azesmway** [comment]
Hi
are you using the latest release?

**Comment by ynqq** [comment]
> Hi are you using the latest release?

Yes I am using the version 0.1.12 but the RN version I am using is 0.66.4

**Comment by azesmway** [comment]
> > Hi are you using the latest release?
> 
> Yes I am using the version 0.1.12 but the RN version I am using is 0.66.4

strange of course, it should work on this version too. i will try to check

**Comment by ynqq** [comment]
> > > Hi are you using the latest release?
> > 
> > 
> > Yes I am using the version 0.1.12 but the RN version I am using is 0.66.4
> 
> strange of course, it should work on this version too. i will try to check
I got the same error trying to use a newer version of RN. I found that the parent is still fetched after executing this code, I don't know if there is something wrong with my development environment.
```js
  System.out.println("getParent1:"+unityPlayer.getParent());
  ((ViewGroup) unityPlayer.getParent()).removeView(unityPlayer);
  System.out.println("getParent2:"+unityPlayer.getParent());
```
this is the output
I hardly know JAVA, not sure if this is the problem
```js
04-27 10:09:57.970 13082 13082 I System.out: getParent1:com.azesmwayreactnativeunity.ReactNativeUnityView{ec96e4f V.E...... ........ 0,0-720,1496 #2d}
04-27 10:09:57.970 13082 13082 I System.out: getParent2:com.azesmwayreactnativeunity.ReactNativeUnityView{ec96e4f V.E...... ......ID 0,0-720,1496 #2d}
```

**Comment by azesmway** [comment]
> > Hi are you using the latest release?
> 
> Yes I am using the version 0.1.12 but the RN version I am using is 0.66.4

Hi
I tested it on the RN you write about - it works without errors and crashes in both Android and iOS

**Comment by ynqq** [comment]
> > > Hi are you using the latest release?
> > 
> > 
> > Yes I am using the version 0.1.12 but the RN version I am using is 0.66.4
> 
> Hi I tested it on the RN you write about - it works without errors and crashes in both Android and iOS

Thanks for the module you created. and take the valuable time to verify the problem
1. When I use the back button at the top there will be no problem
2. When I use goBack App will crash
3. It also crashes when I use the physical return key

**Comment by ynqq** [comment]
> > > > Hi are you using the latest release?
> > > 
> > > 
> > > Yes I am using the version 0.1.12 but the RN version I am using is 0.66.4
> > 
> > 
> > Hi I tested it on the RN you write about - it works without errors and crashes in both Android and iOS
> 
> Thanks for the module you created. and take the valuable time to verify the problem
> 
> 1. When I use the back button at the top there will be no problem
> 2. When I use goBack App will crash
> 3. It also crashes when I use the physical return key
> 
>  1651205941851695.mp4

When I use stack instead of native stack it works fine

**Comment by GunnarMM** [comment]
Switching your stack implementation is not a valid fix for the issue at hand. Can we please re-open this ticket?

I am also facing this issue, while running native-stack.

Unloading the Unity module before navigating back out of the page containing the Unity view does not seem to fix this issue. 
I will try and report back later with additional debug findings, but just wanted to get this message out there.

**Comment by psbdgr8** [comment]
@GunnarMM any solution on this ?

**Comment by GunnarMM** [comment]
We have forked the library and made our changes here:
https://github.com/MediaMonksForks/react-native-unity/commit/bdd1108551b0286490a7e2ff4de09520f9a20cb4

Things are running fine for us since.
