### ISSUE TITLE
Example project cannot be initialised

### ISSUE THREAD

**Issue by DatMoser** [azesmway/react-native-unity#13]
Hey! First of all, thank you for taking the time and creating this module, but unfortunately, your example project does not work for me.

1. I first opened your Unity project, switched to Android, and exported the project to example/unity/builds/android/
2. The first error told me to bump up the minSDKversion to 22 instead of 21, which I did. This resolved this error
3. After running the app, I get the following error on MULTIPLE devices and also the android emulator: 
![image](https://user-images.githubusercontent.com/33175923/165174658-de9e2651-d234-48af-b9d6-e284c305b307.png)

4. According to [This SO Article](https://stackoverflow.com/questions/58877735/how-to-solve-libmain-so-not-found-while-using-unity-as-a-library-in-android-ap), it is suggested to switch from "Mono" to "IL2CPP" as the Scripting Backend and enable "ARM64" as well. Unfortunately, after doing this, the app does not build anymore and fails with the error: 

```
* Where:
Build file 'path/react-native-unity/example/unity/builds/android/unityLibrary/build.gradle' line: 66

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> NDK is not installed
```

Even though NDK IS indeed installed and also working (otherwise, the first attempt would not have been built), I am now pretty much stuck at this point and have already tried to solve the issue for a couple of days, and I would therefore highly appreciate some help. (It should be mentioned, that the unity project works fine when built and run from within Unity)

My setup is:
MacOS 12.3.1 on Apple Silicon
Unity 2021.3.0f1
NDK 24.0.8215888

THANKS!

**Comment by GawdZillaa** [comment]
I think I might have come across the same issue some time ago. What resolved it for me was to create a "local.properties" file inside /android dir and give a reference to your installed NDK. Ive read that the current Unity uses NDK version 21.3.6528147. Hope that helps ya
![locPropHelp](https://user-images.githubusercontent.com/22687683/165414476-4cc5f09d-46c2-45fd-8a18-d738028ce9e1.PNG)

**Comment by DatMoser** [comment]
I appreciate the help, but I have already tried this. This has indeed resolved the NDK error but produces the following error instead:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'path/to/react-native-unity/example/unity/builds/android/unityLibrary/build.gradle' line: 73

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> Process 'command 'path/to/react-native-unity/example/unity/builds/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/il2cpp'' finished with non-zero exit value 4
```

Other people have also experienced this problem on [a similiar module](https://github.com/asmadsen/react-native-unity-view/issues/72), but unfortunately, there is apparently no fix for it... Bummer 🫤

**Comment by azesmway** [comment]
this problem appears when the export from the unity passed with errors - you need to check the android unload settings in the unity

**Comment by DatMoser** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/33175923/165493641-ad61c423-e5be-4304-8a2c-002bb68a9838.png">

It should have worked fine, but the app still produces the same error 😅

(BTW: Thanks for helping, guys! Appreciate it!)

**Comment by azesmway** [comment]
try creating a new unity project
add files to folder as described in readme and export

**Comment by DatMoser** [comment]
I am not sure what you mean by "add files to folder as described in readme" 🙈.
I have just created a new project, switched to android, set backend scripting to IL2CPP, added ARM64, selected `/path/to/react-native-unity/example/unity/builds/android/` as build path and hit build. No errors, as above, but when I try to start the app it crashes again with `finished with non-zero exit value 4`.

Did I miss anything or is there some incompatibility with my Unity, or cause of Apple Silicon?

**Comment by azesmway** [comment]
unfortunately I don’t have M1 and therefore I can’t check the work with Unity on it

**Comment by DatMoser** [comment]
I've just reactivated my old Intel mac and tried it there. It DOES work on it. Even with an AR app. So, apparently, this module cannot be run on M1.

Thank you guys, and I am gonna close this issue now 👍🏻

**Comment by psbdgr8** [comment]
@GawdZillaa this module works on M1 you just have to configure the ndk-build in NDK folder for M1 support

**Comment by moh-hit** [comment]
@psbdgr8 can you explain a bit more about this fix
