### ISSUE TITLE
Xcode v15.3< :: Undefined symbol: __mh_execute_header

### ISSUE THREAD

**Issue by TruAmbition** [azesmway/react-native-unity#131]
I'm getting this error after upgrading to Xcode 15.3 on my secondary machine. Xcode 15.2 works fine on my Primary rig. Just out of curiosity I then upgraded Mac OS to Sequoia (v15.0) and Xcode to v16.0 to try and future proof my build. However, I am still getting the same error.

I created a new React-Native Application, built to device just fine with base react-native code. I then implemented v1.0.10 of this amazing React-Unity package and i'm now getting the error:

**Undefined symbol: __mh_execute_header**

I then took to the Unity project and searched for "__mh_execute_header" and found it in the **UnityFramework.h** file. I'm trying to wrap my head around this now, to see if I can refactor or make sure this method is found but I still wanted to reach out to the community as the latest OS updates are rolled out yesterday.

**Comment by TruAmbition** [comment]
So this code reference is in the UnityFramework.framework/Header/UnityFramework.h that gets generated via building the Unity exported Xcode project > UnityFramework that gets exported to the Products directory in that same Unity Xcode project. Hoping there is some flags I can enable in Unity that may help.

Anyone else running into this?

**Comment by TruAmbition** [comment]
Here is a previous reference. Closing the ticket as this is not package related. However Insightful, given the current way of packaging the UnityFramework and importing as a plugin.

https://discussions.unity.com/t/export-unity-2019-1-3f1-as-ios-framework/745049

**Comment by thechaudharysab** [comment]
I was stuck on this today all of a sudden this error started to pop-up. For me Updating "@azesmway/react-native-unity": "1.0.7" to "@azesmway/react-native-unity": "1.0.11" solved it.
