### ISSUE TITLE
Xcode v15.3< :: Undefined symbol: __mh_execute_header

### ISSUE THREAD

**Issue by TruAmbition** [azesmway/react-native-unity#132]
I'm getting this error after upgrading to Xcode 15.3 on my secondary machine. Xcode 15.2 works fine on my Primary rig. Just out of curiosity I then upgraded Mac OS to Sequoia (v15.0) and Xcode to v16.0 to try and future proof my build. However, I am still getting the same error.

I created a new React-Native Application, built to device just fine with base react-native code. I then implemented v1.0.10 of this amazing React-Unity package and i'm still getting the error:

**Undefined symbol: __mh_execute_header**

I then took to the Unity project and searched for "__mh_execute_header" and found it in the UnityFramework.h file. I'm trying to wrap my head around this now, to see if I can refactor or make sure this method is found but I still wanted to reach out to the community as the latest OS updates are rolled out yesterday.

So this code reference is in the UnityFramework.framework/Header/UnityFramework.h that gets generated via building the Unity exported Xcode project > UnityFramework that gets exported to the Products directory in that same Unity Xcode project. Hoping there is some flags I can enable in Unity that may help.

Anyone else running into this?

**Comment by jb-san** [comment]
Running into the exact same issue. It looks like its due to a change in how the linking works and Unity as a library, found this:

https://stackoverflow.com/questions/78932936/undefined-symbols-for-architecture-arm64-mh-execute-header-unity-as-a-lib

**Comment by TruAmbition** [comment]
> Running into the exact same issue. It looks like its due to a change in how the linking works and Unity as a library, found this:
> 
> 
> 
> https://stackoverflow.com/questions/78932936/undefined-symbols-for-architecture-arm64-mh-execute-header-unity-as-a-lib

Thank you for sharing. Did the code change mentioned in the post resolve this for you? I gave my self the night off. But now I'm considering trying it.

**Comment by jasonatmatterless** [comment]
in RNUnityView.mm 
replace &_mh_execute_header with &_mh_dylib_header

Based on this info
https://developer.apple.com/forums/thread/760227

This fixed the issue for me.

**Comment by jb-san** [comment]
did a fork and pull request:
https://github.com/azesmway/react-native-unity/pull/133
if you want to use it before it is merged just put
```
    "@azesmway/react-native-unity": "jb-san/react-native-unity",
```
in your package.json

**Comment by TruAmbition** [comment]
Thank you both! Tested and confirmed working with a fresh build. This is the best I'm going to sleep all week. Cheers gents! Code on! 🦾🦾🦾

**Comment by TruAmbition** [comment]
Closing this issue as this is resolved via @jb-san 's PR #133 

kind regards

**Comment by TruAmbition** [comment]
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/05c436ed-d49f-4bf5-b952-d7dbbfd3bdaf">


@jb-san  I did another fresh built early this morning, got this error. Took a  nap, made another fresh react-native project, added your forked packaged. and still getting this error. Did you see this at all? By Chance do I need to update another reference? I'm a but baffled as to how I got a fresh build to work once but after that it's been another story. I apologize for reaching out to bother you after confirming it was working but I figured best to lean on the community during a transitional period like this.

**Comment by TruAmbition** [comment]
Here is the boilerplate code I was hoping to get working:

https://drive.google.com/file/d/1Kl8Mwbd39i77sKXPOm1B_bX1HK7GCtPO/view?usp=sharing

Should have backed up my working project from early this morning but given it was a fresh build I figured I had nothing to worry about :( All these years of development have taught me nothing I see :P

**Comment by TruAmbition** [comment]
I forgot I did this at some point. Seems like we need need to update the reference here:

Update line 17 in > unity>builds>ios>UnityFramework.framework>Headers>UnityFramework.h

OLD - Broken: extern const struct mach_header_64  __mh_execute_header;
NEW - Working: extern const struct mach_header_64 _mh_dylib_header;

I guess in my dreams I was hoping this reference would be generated after the RNUnityView.mm file update. But per my testing again with written steps, we still need to update this reference. 

I hope this helps someone that was stuck like me. I also hope we can get this updated so the refeence is correct after we generate UnityFramework.framework.

Ill keep this open again for a bit longer just to make sure all is well before closing.

**Comment by jb-san** [comment]
Im seeing the same error when trying to do production builds, what version of unity are you using ?

**Comment by jasonatmatterless** [comment]
I think the Unity Framework part is depending on the unity version. after updating to 2022.3.47, no change was needed in UnityFramework. its fine on release mode bug debug mode has the error. So i did a conditional fix.

![Screenshot 2024-09-20 at 4 22 13 PM](https://github.com/user-attachments/assets/2f195332-5029-47e4-b274-71d62ca8f4cf)

**Comment by jasonatmatterless** [comment]
I updated unity to 2022.3.47 LTS as my UnityFramework was mismatching yours. There is a discrepancy in behavior between development (debug) mode and release mode.

In this version of unity, no change was needed to UnityFramework.h. and I applied a conditional fix to the RNUnityView depending on the scheme.

![Screenshot 2024-09-20 at 4 27 09 PM](https://github.com/user-attachments/assets/fe13c577-13b1-45d3-9717-093213203582)

**Comment by jasonatmatterless** [comment]
Disclaimer, i have no idea what I'm doing, so this might just be a stopgap until a more proper solution comes along

**Comment by TruAmbition** [comment]
@jb-san im running Unity 2022.3.46f1

I saw ver x.x.47 came out before I shut it down yesterday. After battling Xcode and rebuilding my rig from scratch. I was too nervous to try and upgrade my project again after just upgraded from 2021 to 2022.3.46f1.

I have release builds working with Unity 2022.3.46, Xcode 16.0 on Mac OS 15.0 not on my Intel and silicon machine. 

The trick for me, is you have to update that UnityFramework.h file AFTER you build/generate the UnityFramework.

Here is a subset of my notes for that step. 

Update line 17 in > **unity>builds>ios>UnityFramework.framework>Headers>UnityFramwork.h**
 => **extern const struct mach_header_64 _mh_dylib_header;**

I hope this helps! I might try a brand new project in a unity 2022.3.47f1 and report back. I also wanted to read the change long and see if they had to do anything related to the iOS or Xcode changes.

**Comment by TruAmbition** [comment]
> Disclaimer, i have no idea what I'm doing, so this might just be a stopgap until a more proper solution comes along

Are your builds working?

Please share if you are running into errors. We are in this together. I think your conditional logic is fine. The issue for me was still at the UnityFramework.framework generation level. It was still referencing the __mh_execute_header on line 17 of the unity>builds>ios>UnityFramework.framework>Headers>UnityFramwork.h

I update the line to 

**extern const struct mach_header_64 _mh_dylib_header;**

- Remove/Rebuild pods
- Clean Xcode project
- Rebuild project


Also! Make sure you have the Unity.tsx in your project or your Unity app will crash loop.

**Comment by TruAmbition** [comment]
I got through the FlipperType errors in Release builds by adding adding a user Defined variable in my Xcode workspace under built settings:


<img width="1470" alt="Screenshot 2024-09-20 at 10 05 25 AM" src="https://github.com/user-attachments/assets/6869b650-f598-431d-aa59-83bb8c856801">


This works with my PodFile like so:
`flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled`

Now I get to 99.999% of my Release build and I crash with the "**Undefined symbol: __mh_dylib_header**" at this point, I'm curious if I revert the dylib changes will I get the same error but for __mh_execute_header like we did previously. Either way, a little progress is progress.

**Comment by TruAmbition** [comment]
Update -> Debug and Release builds ar WORKINGGG!

The latest update to the PR that does the conditional logic for debug or release builds fixed this issue for me. I don't even have to go back and edit the UnityFramework.framework file like I did prior to the latest PR revision. Here are my test checkout as follows:

Intel (2017 iMac Pro)
- New Project -> 100/100 (Debug/Release) working
- Existing Project -> 0/0 (Debug/Release) Not working

Silicon (2022 M2 Air)
- New Project -> 100/100 (Debug/Release) working
- Existing Project -> 100/100 (Debug/Release) working

Not bad at all! I'm so very greatful for the community support with this project and bug in particular. I don't mind the Intel issues as much, the goes is to move my project to Arm architecture anyway.
