### ISSUE TITLE
Adjusting Unity Screen Orientation in a React Native Application

### ISSUE THREAD

**Issue by quoctruongkt** [azesmway/react-native-unity#144]
Hi everyone,
I’m developing a React Native application that integrates Unity using the react-native-unity library. My application supports multiple screen orientations controlled by React Native or Native (Java/Kotlin).

However, when Unity runs, the screen orientation doesn’t follow the app’s logic (React Native or Native) but instead behaves according to Unity’s settings. This inconsistency affects the overall user experience.

Is there a way to make Unity follow the screen orientation logic from React Native or Native?
Should this be handled in React Native, Native, or Unity?

Thanks

**Comment by TruAmbition** [comment]
I would suggest finding a way to listen/monitor the screen orientation in your react-native app. Then using the messaging system built into this project to communicate between react-native and Unity, use this to call the screen rotation method inside Unity.

I hope this general logic helps
You find your way. As this is not a limitation of the project, your issue will be closed. 

Thank you,

Truman
