### ISSUE TITLE
"Re-mount" UnityView?

### ISSUE THREAD

**Issue by 256hz** [azesmway/react-native-unity#15]
Per the docs

> Unity is unloaded automatically when the react-native component is unmounted

In my case, we're placing the UnityView inside a tab navigator.  I navigate to the tab with the UnityView, it loads properly, and then I navigate away.  When I navigate back to the tab with the UnityView inside it, it doesn't reappear - I only see the page background, which is similar to when I don't give the UnityView any dimensions.

1. Is it possible to "re-mount" Unity once the UnityView once it has been unmounted?
2. If not, is it possible to prevent the Unity library from being unmounted?

I would much prefer solution 1 but would consider the second one as well.  I'm currently testing on Android.

Thanks for looking and any suggestions!

**Comment by azesmway** [comment]
you can try to comment out in file ``src/index.tsx``
```
public componentWillUnmount() {
  this.unloadUnity();   <----
}
```

**Comment by 256hz** [comment]
Thanks for the quick reply.  I don't see any change when I do that.  After playing with it I think navigating away from the tab doesn't unmount the component - code in that block doesn't seem to get called.  I can see when it mounts though.  I'll keep playing with it.

**Comment by 256hz** [comment]
All I've found so far are these three errors when the component comes back into focus:

```
E/unknown:FabricViewStateManager: setState called without a StateWrapper
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x0
E/EGL_emulation: tid 27637: swapBuffers(570): error 0x300d (EGL_BAD_SURFACE)
```

It appears to be coming from whatever is creating the 3D display, which seems like it could be this library or the Unity project I'm importing.  Did you ever see this in testing?  Are you able to navigate away and return to a UnityView on Android?

**Comment by azesmway** [comment]
in android, I did it specifically to slow down the Unity, because if it works after exiting the screen, then the phone’s battery will run out very quickly
if you want - you can control stopping the Unity on exit

```
    @Override
    protected void onDetachedFromWindow() {
        ReactNativeUnity.addUnityViewToBackground();   <------ this
        super.onDetachedFromWindow();
    }
```

**Comment by 256hz** [comment]
That works for now!  Thank you.  I'll close this and look into reinitializing the view some other way.
