### ISSUE TITLE
unity not reload

### ISSUE THREAD

**Issue by Nuengnakhap** [azesmway/react-native-unity#2]
unity does not reload when I first enter the unity screen and close the screen then I enter the unity screen again it outputs the last state before I close the screen.

**Comment by azesmway** [comment]
When using the "Unity as a Library" Feature to integrate Unity into your native iOS application you won't be able to fully terminate Unity and return to your native App.

As stated in the [Unity Documentation](https://docs.unity3d.com/Manual/UnityasaLibrary-iOS.html) on integrating Unity into native iOS applications you are able to call the method - (void)unloadApplication; on the UnityFramework instance to release most of the memory it occupies, but not all of it. You will be able to run Unity again after doing so.

**Comment by Nuengnakhap** [comment]
but old version it reload unity when I re-enter again

https://github.com/azesmway/react-native-unity-play

**Comment by azesmway** [comment]
I'll check, maybe something has not been transferred to the new version

**Comment by azesmway** [comment]
> I'll check, maybe something has not been transferred to the new version

Please test current version 0.1.5

**Comment by Nuengnakhap** [comment]
It not work.
How to run unity again when use "unloadApplication" ?
Now when I re-enter unity again It stays on the same page before closing unity. Can't press anything in unity's screen.

**Comment by azesmway** [comment]
i made a video from my phone with the unity project
https://drive.google.com/file/d/1ql3XOHqsRgCMrypGjefLrUweC6nWA6DF/view?usp=sharing

**Comment by Nuengnakhap** [comment]
What were you changed in version 0.1.15?
I see you change only the readme in git commit.

**Comment by Nuengnakhap** [comment]
Can you send your unity project to me?
I will test on your project.

**Comment by azesmway** [comment]
this is my working draft and i can't send it to you
in "example" folder i made a working example, it works also

**Comment by Nuengnakhap** [comment]
I try to test on your unity example project.
The screen is stuck after re-enter again.

https://user-images.githubusercontent.com/31353598/160885551-93876890-ba7e-459a-beb6-fd881c30803b.MP4

**Comment by azesmway** [comment]
Thank you for your help in finalizing the plugin. 
I fixed the problem and released a new release.
Release 0.1.6

**Comment by Nuengnakhap** [comment]
It's already working. Thank you so much.
