### ISSUE TITLE
[Question] Do I need to clone this repo first and then run npm in the cloned folder?

### ISSUE THREAD

**Issue by ROBYER1** [azesmway/react-native-unity#33]
Mainly asking as the Readme installation guide, it simply says to run the npm command `npm install @azesmway/react-native-unity
` which doesn't result in a folder structure with anything except the package files and a folder of node modules - no Unity folder etc. Might be worth mentioning in the Readme that you need to clone the project and run the npm command in the folder.

**Comment by azesmway** [comment]
The Unity folder and everything else can be located anywhere, it was easier for me, I did it for myself. You can customize everything for yourself.

**Comment by ROBYER1** [comment]
Thanks, I'll close this as I'm just setting up now and thanks for the fast response
