### ISSUE TITLE
Problem with the Unity Export

### ISSUE THREAD

**Issue by Dhilip-Palanisamy** [azesmway/react-native-unity#37]
I used the sample Unity project from your repo and successfully exported it for the Android platform. Then I followed all the instructions from the README.md file for using the exported Unity as a library in RN.

When I installed the RN-Unity build on my Android phone, I am experiencing the below issue.

![unity_error](https://user-images.githubusercontent.com/31561555/181509960-e8c193aa-979a-4a45-a9ef-74c39941be77.jpg)

The Unity build was exported with the below settings:

Scripting backend : Mono
Target architecture: Armv7

Later I came to know that we need to export the Unity project with IL2CPP scripting backend and Arm64 target architecture should be enabled.

I tried that but now I am experiencing below issue while exporting Unity project itself.

*Exception: /Applications/Unity/Unity.app/Contents/il2cpp/build/deploy/net471/il2cpp.exe did not run properly!*

Can you please help me to fix these issues?

Kindly let me know if you need any other details from your end.

Thanks!

**Comment by iamjessroman** [comment]
Do not compile on emulator only on real device

**Comment by bekazandukeli** [comment]
This issue helped me when I exported arm64 [https://stackoverflow.com/questions/55974331/unity-export-android-64-bit](url)
Also take a look at this: https://github.com/azesmway/react-native-unity/issues/46#issuecomment-1272150956

**Comment by pihels** [comment]
Just adding to here that I did all the config correctly on Unity side, but still got the same error.
What finally helped was adding the same abiFilters to android/app/build.gradle file as are present in unity/builds/android/unityLibrary/build.gradle:

so in my case I had to add
    defaultConfig {
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

Also check out this thread for some other solutions if this doesn't fix it for you:
https://forum.unity.com/threads/app-not-working-on-some-devices-failed-to-load-libmain-so.1031137/
