### ISSUE TITLE
How to build when unityFramework has its own Pods project

### ISSUE THREAD

**Issue by danieldormann** [azesmway/react-native-unity#41]
Hi,

first of all thanks a lot for your work. So far everything works flawlessly when we stick to simple examples. We are in the situation though, that we have Firebase as a dependency. One of the implications is that when we export the unity project, we get a workspace and a second project for cocoa pods. 

Sadly I am not proficient enough in the iOS build stack to exactly know which steps are necessary. When adding both projects it will fail with 

`/Users/daniel/Desktop/Dev/156_eswb-app/node_modules/@azesmway/react-native-unity/ios/ReactNativeUnityView.h:4:10: 'UnityFramework/UnityFramework.h' file not found`

Funny enough, I can build the unityFramework just fine, when selecting its scheme and hit build. The error persists though when going back to the Main Project and trying to run. Build phases and everything is set up like in the guide and as said: With a simple project it works flawlessly. 

That's the project structure as of now, first Pods is the UnityFramework Pod project:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/26373/188679522-2712cc7a-2b73-4649-a93a-2f0d1667c48f.png">

I'm thankful for any ideas, hints, guidances :)

**Comment by danieldormann** [comment]
Sorry, you can close this. For some reason the UnityFramework.h was missing in the header file references. Just adding it worked

**Comment by VanCoding** [comment]
@danieldormann I'm having the exact same problem. Cleaning the project in all ways imaginable didn't help.
Where did you add the reference?

**Comment by VanCoding** [comment]
@danieldormann I finally managed to make it work. For me, building the UnityFramework first by selecting it in the title-bar and hitting build, and then selecting & building the main project afterwards did the trick.

@azesmway Is it possible that this is needed sometimes? If yes, it could be included in the readme steps.

**Comment by azesmway** [comment]
5. In Build Phases remove UnityFramework.framework from Linked Binary With Libraries
6. In Build Phases move Embedded Frameworks before Compile Sources ( drag and drop )

**Comment by VanCoding** [comment]
@azesmway Ah, I think I did this on the main project, but not on the "Unity-iPhone" project. If that's the issue, then even better :) Thanks!

**Comment by danieldormann** [comment]
You probably need to change the Podfile of unity-iphone to make use of modular headers. Otherwise it will most likely crash on some devices:

`
#use_frameworks!
use_modular_headers!
`

**Comment by VanCoding** [comment]
@azesmway Interesting.. I get the same error message with your example project.

I cloned the repo, cd'ed into example/ios ran `npm install` and then `pod install`, then opened the project using XCode and tried to build.
But somethings off anyway, the "Unity-iPhone" project is greyed out, and i can't select UnityFramework scheme this time 
![grafik](https://user-images.githubusercontent.com/595361/189098635-7084c365-2a8c-492c-96c9-42507b89448b.png)
![grafik](https://user-images.githubusercontent.com/595361/189098771-692309b2-69eb-49d0-9160-b6c2a1d1e0ba.png)

**Comment by azesmway** [comment]
You cloned the example, the example contains the sources of the Unity project and which you need to build and add to the example!
