### ISSUE TITLE
String resource ID #0x0

### ISSUE THREAD

**Issue by BedkowskiP** [azesmway/react-native-unity#42]
![image](https://user-images.githubusercontent.com/10899007/189314336-240cd7de-c35b-4f0b-a944-41d9cc705327.png)

Code:
```
import React, { useRef, useEffect } from 'react';
import UnityView from '@azesmway/react-native-unity';
import { View, Button, Text } from 'react-native';

interface IMessage {
    gameObject: string;
    methodName: string;
    message: string;
  }

const Unity = ({ navigation }) => {
  console.log('Open Unity')
  const unityRef = useRef(null);
    
    useEffect(() => {
      if (unityRef.current) {
        const message: IMessage = {
          gameObject: 'gameObject',
          methodName: 'methodName',
          message: 'message',
        };
        unityRef.current.postMessage(message.gameObject, message.methodName, message.message);
      }
    }, []);
    
    return (
      <View style={{ flex: 1 }}>
        <Button title='Go back Home' onPress={() => navigation.navigate('Home')} />
        <UnityView
          ref={unityRef}
          style={{ flex: 1 }}
          onUnityMessage = {(result) => { console.log('onUnityMessage', result.nativeEvent.message) }}
        />
      </View>
    );
    
};

export default Unity;
```

Seems like my project has problem with unityRef/UnityView.

without 
`<UnityView
          ref={unityRef}
          style={{ flex: 1 }}
          onUnityMessage = {(result) => { console.log('onUnityMessage', result.nativeEvent.message) }} />`
project seems to work fine.
![image](https://user-images.githubusercontent.com/10899007/189314949-d6088ac6-424d-484d-bd3d-d4c3a7a5279c.png)

Any idea how to fix it?

**Comment by wolfdavo** [comment]
@BedkowskiP What did you do to fix it? Getting the same error

**Comment by Agreafel** [comment]
This fix can be found in step 5 of the README instructions for setting up android. No sweat for missing it, I missed it for quite some time as we;;
