### ISSUE TITLE
App crashes. Failed to load 'libmain.so'

### ISSUE THREAD

**Issue by late17** [azesmway/react-native-unity#46]
When launching an app there is an error almost on all phones.
Your Hardware does not support this app.
Failed to load 'libmain.so'
java.lang.Unsatisfied.Error ...

**Comment by vazarkevych** [comment]
Is there any review guys? We faced the same problem when building the app.

**Comment by relaxxpls** [comment]
Select target architecture of the devices you are running. If its Pixel on an Emulator, specifically select x86 in Target Architecture.

![image](https://user-images.githubusercontent.com/63250453/194674018-e86aeecc-d2d6-4fcb-892d-cbd39b0ec139.png)

**Comment by vazarkevych** [comment]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/94451639/195093010-61980a6e-5492-4146-b2be-6f7902271686.png">
Here in jniLibs should also be present ARM64, am I right?

**Comment by azesmway** [comment]
![UM 2022-10-11 16-00-30](https://user-images.githubusercontent.com/15251391/195097651-08a96602-aaea-484f-8ccf-000858db01be.jpg)

**Comment by Ridwan226** [comment]
@azesmway 


what if i get a problem

Execution failed for task ':unityLibrary:BuildIl2CppTask'.

**Comment by azesmway** [comment]
I need to study each specific case, there can be many reasons

**Comment by late17** [comment]
Thanks for reply, it helped. Have a nice day.

**Comment by pihels** [comment]
Just adding to here that I did all the config correctly on Unity side, but still got the same error.
What finally helped was adding the same abiFilters to android/app/build.gradle file as are present in unity/builds/android/unityLibrary/build.gradle:

so in my case I had to add
```
    defaultConfig {
        ndk {
            abiFilters 'arm64-v8a'
        }
    }
```

Also check out this thread for some other solutions if this doesn't fix it for you:
https://forum.unity.com/threads/app-not-working-on-some-devices-failed-to-load-libmain-so.1031137/
