### ISSUE TITLE
'UnityFramework/UnityFramework.h' file not found

### ISSUE THREAD

**Issue by BunieVu** [azesmway/react-native-unity#52]
I have followed your instructions but i'm getting this error in IOS.
Xccode version: 14.0.1
RN version: 0.70.4
<img width="1426" alt="Screen Shot 2022-10-26 at 13 44 09" src="https://user-images.githubusercontent.com/54257370/197957470-5042dfc9-395c-4bda-bfec-ccec729c20b8.png">

**Comment by BunieVu** [comment]
I have resolved this issue

**Comment by jsellam** [comment]
Can you say how please ? I have the same issue. 
thx

**Comment by BunieVu** [comment]
Run build unity framework before you run build your project.
<img width="1397" alt="Screen Shot 2022-10-28 at 10 03 31" src="https://user-images.githubusercontent.com/54257370/198488215-9a3b5037-c5fa-45c9-bf74-341dab3dc6a2.png">
