### ISSUE TITLE
iOS: Stored data from unity is not working

### ISSUE THREAD

**Issue by rcorrie** [azesmway/react-native-unity#64]
On iOS, our Unity game stores some data locally.

When the app is killed and reopened, Unity is not able to find/retrieve the previously stored data.

**Comment by Agreafel** [comment]
More of a unity save implementation question. Do you utilize any way to apply the save data onto the unity app? Unity will always start fresh unless you use some sort of save files or utilize the player prefs that unity provides, then you have to be certain unity pulls the data out from the data to apply it to the app.
https://docs.unity3d.com/ScriptReference/PlayerPrefs.html

**Comment by rcorrie** [comment]
@Agreafel thanks, our Unity developer figured out the issue on his end. The app state listeners weren't properly set up.
