### ISSUE TITLE
Practical way to temporarily disable the plugin to work with iOS simulator?

### ISSUE THREAD

**Issue by serdarcevher** [azesmway/react-native-unity#90]
Greetings. I've been using an older version of the plugin (0.3.1) since a few months, and I was able to disable it on the fly when needed (to work in iOS simulator for other parts of the app). I can't find an equivalent way to do this with the new (1.0.6) version.

Previously, whenever I was going to work on "other" parts of the app (free from Unity), I was removing Unity related parts from project.pbxproj file, then removing the Unity-iPhone project reference from the workspace and I was then able to work with iOS simulator perfectly. Even the import UnityView statement wasn't causing a problem (I was simply using basic replacement to mimic Unity functionality).

Now with the new version, I can't even make Xcode build the project without the unity/builds/ios folder. Is it possible to add something like IF (TARGET_OS_SIMULATOR) - skip kinda thing?

**Comment by serdarcevher** [comment]
After making the new version work in my real device, trying to compile the app for the iOS simulator resulted as: 
_"Building for iOS Simulator, but linking in dylib built for iOS, file '[project_root]/node_modules/@azesmway/react-native-unity/ios/UnityFramework.framework/UnityFramework' for architecture arm64'_

<img width="433" alt="Screenshot 2024-01-20 at 00 12 51" src="https://github.com/azesmway/react-native-unity/assets/824239/06699105-e128-4bce-b5c6-812bf9b1cac0">

**Comment by serdarcevher** [comment]
For anyone interested: In order to be able to run the project in the simulator, I needed to exclude arm64 for the simulator architecture, **both** from **my project** and the **Pod project**, as described in here: https://stackoverflow.com/a/63955114

**Comment by Jpoliachik** [comment]
For anyone using Expo, I was able to accomplish this with a custom plugin that 
- modifies the Xcode project settings to exclude simulator arm64 for the main app
- modifies the Podfile to set each Pod to exclude simulator arm64 (does this with a slightly dangerous string replacement, so it could break in the future...)

Here are the two functions that accomplish that, to be used in an Expo plugin. 

```typescript
const withXcodeProjectMod: ConfigPlugin = (config) =>
  withXcodeProject(config, async (config) => {
    const xcodeProject = config.modResults
    const configurations = xcodeProject.pbxXCBuildConfigurationSection()

    /*
      Update the build settings to exclude arm64 architecture for simulator builds
      This is necessary to avoid the "UnityFramework.framework" not found issue when building for simulator
      since the Unity project does not support ios simulator
    */
    const excludedArchsValue = "arm64"

    // Iterate over each configuration and update the build settings
    Object.entries(configurations).forEach(([key, configObj]) => {
      const { isa, buildSettings, name } = configObj as any
      if (isa === "XCBuildConfiguration" && (name === "Debug" || name === "Release")) {
        if (!buildSettings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"]) {
          buildSettings['"EXCLUDED_ARCHS[sdk=iphonesimulator*]"'] = excludedArchsValue
          console.log("foudn it! setting EXCLUDED_ARCHS to arm64")
        }
      }
      console.log("config", { configObj })
    })

    return config
  })

/*
  Adjust the Podfile to exclude arm64 architecture for simulator builds
  for all the pods in the project
  This is also necessary in order to get the Unity project to build for simulator
  */
const withPodfileDangerouusMod: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "ios",
    (config) => {
      /*
      We need to do a 'dangerous' mod to the Podfile
      and add lines to the post install hook to exclude arm64 architecture for simulator builds
      */
      const file = path.join(config.modRequest.platformProjectRoot, "Podfile")
      const contents = fs.readFileSync(file).toString()

      // look for the closing bracket of the `react_native_post_install` block, insert stuff on the following lines
      const regex = /react_native_post_install\([^)]+\)\s*/
      const newLine = `
installer.pods_project.build_configurations.each do |config|
  config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end\n\n`

      const newContents = contents.replace(regex, "$&\n" + newLine)
      console.log(newContents)
      fs.writeFileSync(file, newContents)
      return config
    },
  ])
```
